[package]
name = "outlaw"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34"
time = "0.1"
lazy_static="1.4"
[[bin]]
name = "outlaw"
path = "outlaw.rs"
